version: 2

project_name: Uzeltok

before:
  hooks:
    - go mod tidy

builds:
  - id: server
    main: ./cmd/server
    binary: Uzeltok-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X 'Uzeltok/internal/buildinfo.Version={{.Version}}' -X 'Uzeltok/internal/buildinfo.GithubURL=https://github.com/momoirodouhu/Uzeltok'

archives:
  - formats: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

release:
  github:
    owner: momoirodouhu
    name: Uzeltok
