version: '3.8'

services:
  uzeltok:
    image: ghcr.io/momoirodouhu/uzeltok:latest
    container_name: uzeltok
    ports:
      - "8080:8080"
    environment:
      - ADMIN_PASSWORD=change_here
    volumes:
      - ./data:/app/data
    restart: unless-stopped